install:
  - source ./support/texlive.sh

cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive

script:
  - source ./support/local.sh
  - source ./support/run.sh
  # Make test theses
  - cd test
  - xelatex  -interaction=nonstopmode test
  - lualatex -interaction=nonstopmode test
  - xelatex  -interaction=nonstopmode test-en
  - lualatex -interaction=nonstopmode test-en
